# New Kubernetes Deployment for CI/CD Pipeline
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - sleep
            - "3600"
