# New Kubernetes Deployment for CI/CD Pipeline
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-k8s
spec:
  replicas: 4
  selector:
    matchLabels:
      app: github-k8s
  template:
    metadata:
      labels:
        app: github-k8s
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - sleep
            - "3600"
